spring:
    data:
        mongodb:
            authentication-database: admin
            database: trustcertificationsystem
            host: mongo
            port: 27017
            username: ENC(vb0mlnK7rEnJyAw459NoSg==)
            password: ENC(dT+5AMBOTacnNnBTqxt12g==)

  
## Trust Certification System Props
trust:
    certification:
        system:
            chain-id: 85
            wallet-directory: /opt/wallets
            client-address: http://192.168.1.39:8545
            root-public-key: "0xE545f3b554175BABcBeF152D4516Ff90455095EE"
            root-private-key: ENC(7k5dAObOTy1arUeaWbSG1mldiWDR/3mIJHqqRnXivkXaTpjYkYMNTfy8Ivktio6I2qnT+QK6DetaWpIw3AZqVRhBoPRORiCcNGYwJZE5ly0=)
            gas-price: 1000000000
            gas-limit: 993613
            token-management-contract-address: "0x4e690116b461DB7E23f78E991F94dB8Eb1E26B55"
            certification-authority-contract-address: "0xc341CC01DB1cA6A2Eb1C864EBC8a2AADe725D55e"
            certification-course-contract-address: "0x8f2A3B132023Bf33A25617B3C9B2Ca7896053441"
            trust-certification-contract-address: "0x6dF5B51DA5587611eAFd0AA7727f0a8CAf9B6B7C"
            trust-ether-faucet-contract-address: "0x8F3FD73CbF7081D4E764b4ff7708cBB62950D301"


### Vault Config
vault:
    uri: http://vault:8200
    token: hvs.snV6aFdHVyjzAO3PIk8N0ygh
    wallet-path: tcs-v1/wallets/


#### Channels
channels:
    new-user-registration: newUserRegistrationProcessor-out-0
    certification-course-registration: certificationCourseRegistration-out-0
    new-certification-request: newCertificationRequest-out-0


## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ethsftp
    password: ethsftp00
    remoteFolder: keystore/

## IPFS Config
ipfs:
    ipv4:
        address: 127.0.0.1
        port: 5001

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  com.dreamsoftware.blockchaingateway: DEBUG
  logging.level.org.web3j.protocol.http: TRACE
