spring:
    data:
        mongodb:
            authentication-database: admin
            database: ${MONGO_DB}
            host: mongo
            port: 27017
            username: ${MONGO_ROOT_USER}
            password: ${MONGO_ROOT_PASSWORD}

  
## Ethereum Config
ethereum:
    chain-id: 85
    wallet-directory: /opt/wallets
    client-address: http://192.168.1.39:8545
    root-public-key: ENC(MCWv+IGYU9JhHkyx4X/kUQRY3m1J3HqxYI4fkEZLp4mcS6irdOFytvsOw1EwvG90/qaXINvwqyI=)
    root-private-key: ENC(ari+RGHwCGuqlTyrmBCUFSYiGUH5G8nIieWa4mYaV8Crjho5sCnDcit1DVfaVX8Vn+D7o717ZmHdPsb7nGzOimSGeKPHEmzXfuXTkFnJvlk=)
    gas-price: 1000000000
    gas-limit: 993613
    token-management-contract-address: ENC(ZTyJ8puktc1UOECGhqIj9p+WaozMB1maSwpZz0qBZFg9+ny/i4D6/m251TVWoGC9ZPSo1leFV2s=)
    certification-authority-contract-address: ENC(0UPZ3gtqmtVXoQq0j7RaTqjJ+qh1IhZucYcWiQyq+sR1SDsGwp1dC9T3BIhix3ZqzxzybyM6btc=)
    certification-course-contract-address: ENC(afWDiZxgmvDijCx2EEoE8daNh7Fce+z7UtXS+8DGqOxOsAe6FuL9oKsbZq+fm1joVuV/5e9kxwk=)
    trust-certification-contract-address: ENC(t5qs/yYO/7VOkNXHuCtIlPncyWdOcGZEhBYzA3psSo3SBJxtKLYZeD7m//oMmQ8ZBtn84EDk3Mg=)
    trust-ether-faucet-contract-address: ENC(OFafdawJK/SB82HXkm7NcUHv1zyGyuLPdWazX3c11MeaU40+NPwD0RaMl+pCuPTEaWWfCEXAE8o=)
            
### Vault Config
vault:
    uri: http://vault:8200
    token: ENC(2q19s7D0xtI/CyJFDT5L2MYmWoI0CYAUAqvlNljctM8S5n3eizsabA==)
    wallet-path: tcs-v1/wallets/


## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ENC(hc4XhZ8OKfdY2IiHOi12qA==)
    password: ENC(o8n88SOqS0YTLHY7WPUL3RYn6Er40+aW)
    remoteFolder: keystore/

## IPFS Config
ipfs:
    ipv4:
        address: 192.168.1.39
        port: 5001

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

# Crypt Service Config
crypt:
    password: ENC(sucS/grvNPGMxNFcfR3FsbzEWg3a0RTceOemhivFqKcQzRjC7FYXVCKxU2ptkWcv)
    salt: ENC(+D/+VILc9K88IgZe9zTtAmRHaXRRI6cenS/3A9vrKH2/uJF/rAZPjw==)
    separator: ENC(wgn3uHGzjW0gjcos7FqhtHam27cxgjEoeOQ2yJUMQ0hXOjqAYVkT8XiGfItuo7jz)

######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
        algorithm: PBEWithMD5AndTripleDES
        

logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  org.springframework.ldap: DEBUG
  com.dreamsoftware.tcs: DEBUG
  logging.level.org.web3j.protocol.http: TRACE
