spring:
    data:
        mongodb:
            authentication-database: admin
            database: ${MONGO_DB}
            host: mongo
            port: 27017
            username: ${MONGO_ROOT_USER}
            password: ${MONGO_ROOT_PASSWORD}
    # Cache Config
    cache:
        type: redis
    redis:
        database: 0
        host: redis-server
        port: 6379
        password: ENC(tKlt1SAdBmmVr17iF0rEJ0keFiaIATo3unPFuH09ymHnqVfjMAzBQKKF21MRXO45)
        timeout: 60000

  
## Ethereum Config
ethereum:
    chain-id: 85
    wallet-directory: /opt/wallets
    client-address: http://192.168.1.39:8545
    root-public-key: ENC(MCWv+IGYU9JhHkyx4X/kUQRY3m1J3HqxYI4fkEZLp4mcS6irdOFytvsOw1EwvG90/qaXINvwqyI=)
    root-private-key: ENC(ari+RGHwCGuqlTyrmBCUFSYiGUH5G8nIieWa4mYaV8Crjho5sCnDcit1DVfaVX8Vn+D7o717ZmHdPsb7nGzOimSGeKPHEmzXfuXTkFnJvlk=)
    gas-price: 1000000000
    gas-limit: 993613
    token-management-contract-address: ENC(hLYpXLaBIFP7HceHhoR+qKrSBE/vjl0D6jeX6ohpcWX2E2yGntIvJmhN9V6jTW9zKD0uOgWZZoQ=)
    certification-authority-contract-address: ENC(cMnhAm8XyJFUCfGKccnL0Fai3JFq+EhSWUYahhAYFXOrVVatBSCgu0spRBBn6mYfh28mLRmsnmo=)
    certification-course-contract-address: ENC(NrhAu9cqvZrs3+/mpLdH67DC4HcCTjRL7Ad+yWcjwt5+vmexOvCUCMqd9DbUAklF2PfsEu4b1nI=)
    trust-certification-contract-address: ENC(w1zVN9sNevR5Kjyb9oRUoWnkwkny+1/v5bd1Ke+nkL3O7ovLtFFQucsvkuMcc+sGTd41BPhFkHs=)
    trust-ether-faucet-contract-address: ENC(3i+wHzIpPomXJYMuhZ2jDBRln8FGPIWQa0+MsqoUmRjUVHtrEuU/7R0MQ4X6p8ygGdbQNAbZUkw=)
            
### Vault Config
vault:
    uri: http://vault:8200
    token: ENC(0kQNOOi/w7gpCA266y2n86pflNKerGH2A/2eBczcKoM/GU4S3lydDA==)
    wallet-path: tcs-v1/wallets/


## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ENC(hc4XhZ8OKfdY2IiHOi12qA==)
    password: ENC(o8n88SOqS0YTLHY7WPUL3RYn6Er40+aW)
    remoteFolder: keystore/

## IPFS Config
ipfs:
    ipv4:
        address: 192.168.1.39
        port: 5001

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

# Crypt Service Config
crypt:
    password: ENC(sucS/grvNPGMxNFcfR3FsbzEWg3a0RTceOemhivFqKcQzRjC7FYXVCKxU2ptkWcv)
    salt: ENC(+D/+VILc9K88IgZe9zTtAmRHaXRRI6cenS/3A9vrKH2/uJF/rAZPjw==)
    separator: ENC(wgn3uHGzjW0gjcos7FqhtHam27cxgjEoeOQ2yJUMQ0hXOjqAYVkT8XiGfItuo7jz)

######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
        algorithm: PBEWithMD5AndTripleDES
        

logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  org.springframework.ldap: DEBUG
  com.dreamsoftware.tcs: DEBUG
  logging.level.org.web3j.protocol.http: TRACE
