spring:
    data:
        mongodb:
            authentication-database: admin
            database: ${MONGO_DB}
            host: mongo
            port: 27017
            username: ${MONGO_ROOT_USER}
            password: ${MONGO_ROOT_PASSWORD}

  
## Ethereum Config
ethereum:
    chain-id: 85
    wallet-directory: /opt/wallets
    client-address: http://192.168.1.39:8545
    root-public-key: ENC(MCWv+IGYU9JhHkyx4X/kUQRY3m1J3HqxYI4fkEZLp4mcS6irdOFytvsOw1EwvG90/qaXINvwqyI=)
    root-private-key: ENC(ari+RGHwCGuqlTyrmBCUFSYiGUH5G8nIieWa4mYaV8Crjho5sCnDcit1DVfaVX8Vn+D7o717ZmHdPsb7nGzOimSGeKPHEmzXfuXTkFnJvlk=)
    gas-price: 1000000000
    gas-limit: 993613
    token-management-contract-address: ENC(wYqsAxN8B825GYqzauuhp5K7ybrcvoBRpM3okAfDlzBtTr62yaw9o38NVYC8RNHphyyXnYvnswU=)
    certification-authority-contract-address: ENC(+JmWc0vzTdS9VU6DZXkDu/JCNms+KNcx5dM9aQt/nBllaEYzMoc9GIy8+PXxlAkL6iFtqwed6E4=)
    certification-course-contract-address: ENC(Le4QYMrnzlm1PMZdDqC9yYUCcjBI5dqzDE4FiLnD5US4A1lEB6yc+QeS5ReexSJeKyCGugtNvK4=)
    trust-certification-contract-address: ENC(+gJK/HlNvSuVgNNjBh6ilwRBQWlL2CoXU6vZeeFaETlD7Tu6XHK/8M5OjRT5IgT+xmcQDLtcvvY=)
    trust-ether-faucet-contract-address: ENC(4hq221iB7/ybQaSX5CCGPxnQI/wB+TsnyouIheFX8wcT0rCD9hKKtla0/1SPk6tvRK1YzwTG+zE=)
            
### Vault Config
vault:
    uri: http://vault:8200
    token: ENC(m9S0fLaRPRZjDRcv44/CZzpX0bv1H8J5klgF/wyEUt5woae0LCzI0Q==)
    wallet-path: tcs-v1/wallets/


## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ENC(hc4XhZ8OKfdY2IiHOi12qA==)
    password: ENC(o8n88SOqS0YTLHY7WPUL3RYn6Er40+aW)
    remoteFolder: keystore/

## IPFS Config
ipfs:
    ipv4:
        address: 192.168.1.39
        port: 5001

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

# Crypt Service Config
crypt:
    password: ENC(sucS/grvNPGMxNFcfR3FsbzEWg3a0RTceOemhivFqKcQzRjC7FYXVCKxU2ptkWcv)
    salt: ENC(+D/+VILc9K88IgZe9zTtAmRHaXRRI6cenS/3A9vrKH2/uJF/rAZPjw==)
    separator: ENC(wgn3uHGzjW0gjcos7FqhtHam27cxgjEoeOQ2yJUMQ0hXOjqAYVkT8XiGfItuo7jz)

######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}
        algorithm: PBEWithMD5AndTripleDES


management:
    endpoint:
        health:
            enabled: true
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
        jmx:
            exposure:
                include: '*'
        
logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  org.springframework.ldap: DEBUG
  com.dreamsoftware.tcs: DEBUG
  logging.level.org.web3j.protocol.http: TRACE
