spring:
    data:
        mongodb:
            authentication-database: ENC(v0XrtgGRRooy/ws2Zl2b7A==)
            database: ENC(wuO4zj9wryQbbblUsLTPVBmmkae5UiuDRcLQTUbfSzMdWehCzhkBLA==)
            host: mongo
            port: 27017
            username: ENC(HtnPXTvQy9tOUMVdn92hfw==)
            password: ENC(LaemS97jNcjhe2khU5blYg==)
    # Mail
    # output of emails
    mail:
        host: smtp.gmail.com
        port: 587
        username: ENC(4q6DRq1kHLEPN183mZhxu8h5ae1P27AGqCkdwF0WCSeG45XW/Ph1jA==)
        password: ENC(0gidX1BItOmyWVdGC1AiVFrrxLp5g4I8Kad7njt8e5P23inbKSorBg==)
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
                    ssl.trust: smtp.gmail.com
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000

  
## Trust Certification System Props
trust:
    certification:
        system:
            chain-id: 85
            wallet-directory: /opt/wallets
            client-address: http://192.168.1.39:8545
            root-public-key: ENC(BfORbisouJS2+iVSM93dQk3KUDko016iWNhwwGJujTypZJiTF4YmOaA7HJ/nahBBkcUzuTECB0o=)
            root-private-key: ENC(DBPrOVkSHBrKFVSQI9o1CI20OssGVBFjh+i353k2CN0FRarwYcD3Qfhqng4hsR6wbYwg//CDmgAo36y87M/mOLcTYBsliLhp17uoVUsPbvw=)
            gas-price: 1000000000
            gas-limit: 993613
            token-management-contract-address: ENC(DDzVvELij/ZrWHN1ct6zaHJSw/Tm5a4ruhCeONW69svIdgfWHsyNG5UUZe6X02gI1KI1Xv1AFkc=)
            certification-authority-contract-address: ENC(5KeNtOH5k54faziexSyJL3t93b0lg3cHW1BiqN/F/s3VM78xwKsbYVkeK0R45F0b6MSR6binILQ=)
            certification-course-contract-address: ENC(DxtCwuYWktMaUsywz+3bA7Ezz8iuzzh33M8nXf1WOEnNb7fF/XklauXr09yStvx3e+reZD8/Dlo=)
            trust-certification-contract-address: ENC(2FBGXAP6w9F/lcL/8SnVrlpZp6dVyTc+2McuUHwbBQ+/SP3INRHkxekDvPALKGDfGbLtasGkACs=)
            trust-ether-faucet-contract-address: ENC(P1mt9BGIkXiBCe7NGgXFy6JcaEOKtqTM/+W/fduHoPEMNHyMTMghhNibHLviEis/BF7aj0rHI64=)


### Vault Config
vault:
    uri: http://vault:8200
    token: ENC(hEJvvT6lJ5Jzx3sWcCR6c7pnw7SzeSMHRR4A1RhzaxHSQ6S3yind+g==)
    wallet-path: tcs-v1/wallets/

# Mail Properties
mail:
    templates:
        base.dir: mail/templates/
        accounts:
            pending-validation: user_pending_validation_mail_template
            user-activated: user_activated_mail_template
    resources:
        base.dir: mail/resources/
    from: ENC(2fhT/KBRBQbae36mvdNRWizBRsmWPfNtHKGVkiUDphs7DDGJz7EPcA==)

#### Channels
channels:
    new-user-registration: newUserRegistrationProcessor-out-0
    certification-course-registration: certificationCourseRegistration-out-0
    new-certification-request: newCertificationRequest-out-0
    new-tokens-order-approved: newTokensOrderApprovedProcessor-out-0


## SFTP Config
sftp:
    hostname: 192.168.1.39
    port: 2222
    username: ENC(hc4XhZ8OKfdY2IiHOi12qA==)
    password: ENC(o8n88SOqS0YTLHY7WPUL3RYn6Er40+aW)
    remoteFolder: keystore/

## IPFS Config
ipfs:
    ipv4:
        address: 127.0.0.1
        port: 5001

# i18n Config
i18n:
    paramname: lang
    default.locale: en_GB
    locale.supported: es_ES,en_GB

######## Encryption Configuration #####
jasypt:
    encryptor:
        password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging.level:
  org.springframework.cloud: DEBUG
  org.springframework.security: DEBUG
  com.dreamsoftware.blockchaingateway: DEBUG
  logging.level.org.web3j.protocol.http: TRACE
