spring:
  cloud:
    stream:
          function:
              definition: caInitialFundsRequestProcessor;caRegistrationRequestProcessor;caRegisteredProcessor
          kafka:
              binder:
                  brokers: kafka:9092
                  auto-create-topics: true
                  configuration.auto.offset.reset: latest
          bindings:
              caInitialFundsRequestProcessor-in-0:
                  destination: CA-initial-funds-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              caInitialFundsRequestProcessor-out-0:
                  destination: CA-registration-request-v1
              caRegistrationRequestProcessor-in-0:
                  destination: CA-registration-request-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              caRegistrationRequestProcessor-out-0:
                  destination: CA-registered-v1
              caRegisteredProcessor-in-0:
                  destination: CA-registered-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              courseRegistrationRequestProcessor-in-0:
                  destination: CC-registration-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              courseRegistrationRequestProcessor-out-0:
                  destination: CC-registered-v1
              courseRegisteredProcessor-in-0:
                  destination: CC-registered-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
