spring:
  cloud:
    stream:
          function:
              definition: newUserRegistrationProcessor;userRegisteredProcessor
          kafka:
              binder:
                  brokers: kafka:9092
                  auto-create-topics: true
                  configuration.auto.offset.reset: latest
          default:
            consumer:
              concurrency: 2
          bindings:
              newUserRegistrationProcessor-in-0:
                  destination: new-user-registration-v1
                  group: bc-gateway-processor
              newUserRegistrationProcessor-out-0:
                  destination: user-registered-v1
              userRegisteredProcessor-in-0:
                  destination: user-registered-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              courseRegistrationRequestProcessor-in-0:
                  destination: course-registration-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              courseRegistrationRequestProcessor-out-0:
                  destination: course-registered-v1
              courseRegisteredProcessor-in-0:
                  destination: course-registered-v1
                  group: bc-gateway-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
