spring:
  cloud:
    stream:
          function:
              definition: newCertificateIssuedProcessor;newIssueCertificateRequestProcessor
          kafka:
              binder:
                  brokers: kafka:9092
                  auto-create-topics: true
                  configuration.auto.offset.reset: latest
          default:
            consumer:
              concurrency: 2
          bindings:
              certificationManagementProcessor-in-0:
                  destination: certification-management-v1
                  group: tcs-certificate-events-processor
                  consumer:
                    concurrency: 10
                    max-attempts: 3
              certificationManagementProcessor-out-0:
                  destination: notification-delivery-request-v1


# Certificate Generator Config
certificateGenerator:
  base-folder: /opt/generator/
  background:
      innovate: tcs_background_innovate.pdf
      professional: tcs_background_professional.pdf
      standard: tcs_background_standard.pdf
  template-file: tcs_academic_certificate_template.docx
  timestamp-authority: http://sha256timestamp.ws.symantec.com/sha256/timestamp
  keystore:
    file: tcs_keystore.jks
    password: ENC(QLt7JSsTwN1hfLsu3VXObGmfaIRqsDhTYCS8uDbyiS0=)
    certificate-alias: tcs
    type: pkcs12
  signature:
    name: Trust Certification System
    reason: Signature of digital certificates
    contact-info: ENC(YHxRr2kT1/EV9etrCyDh+Y6vPpwkQg9S)
  placeholders:
    ca-name: "[[CA_NAME]]"
    student-name: "[[STUDENT_NAME]]"
    course-name: "[[COURSE_NAME]]"
    student-qualification: "[[STUDENT_QUALIFICATION]]"
    certificate-date: "[[CERTIFICATE_DATE]]"
