server:
  tomcat:
    uri-encoding: UTF-8
  port: 8060

spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka:9092
                    auto-create-topics: true
                    configuration.auto.offset.reset: latest