spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka:9092
                    auto-create-topics: true
                    configuration.auto.offset.reset: latest
            bindings:
                newUserRegistrationProcessor-out-0:
                    destination: new-user-registration-v1
                certificationCourseRegistration-out-0:
                    destination: course-registration-v1
                newCertificationRequest-out-0:
                    destination: new-certification-request-v1
                newTokensOrderApprovedProcessor-out-0:
                    destination: new-tokens-order-approved-v1
            function:
                autodetect: false

# JWT
jwt:
    token:
        header: Authorization
        secret: ENC(taz+v24xKk1PfMFbPCf6BKJ6iAzPIsC2reVW6JIzMU14vkKthnvjXPZO+dDxwT/i)
        expiration: 604800
    route:
        authentication:
            path: /auth
            refresh: refresh

# PayPal Gateway Config
paypal:
    client:
        id: ENC(Fl67YKHtgtLFXSIjkbBmfz0Q+EJoaIggezk7IzJWc5pKTHr7WHRP0FVj8I+/fOKy/OZ6J0SRaD5hpAdqYvhiDAbzQzPCaBwVgYZbqBydFtYYu1iZQJbUpXjlRVQhgeAM)
        secret: ENC(D2Xw9qRaLpqAAvpoUaB4YCo1r9Bif1lEYKO50JUEc9P2Qy09odVx7ifHIb9sL+hQOkXWMusQxWaFzPz5zavXH/ONTSxhtz4l44cWQQtVlDIoWm1dp3474MjyVd0KlZlB)

# Crypto Compare Gateway
cryptoCompare:
    baseUrl: https://min-api.cryptocompare.com
    apiKey: ENC(XX7EPAE/7iSPj+CQ0tHFA+jY1ITHXLf8iJh08R6W+u6IAuk5l28kIAVhHzDBWzH7PxTrLD++79pGuuN8Ih/MM4k35w/GMTTukOJIElMmmj4=)

# Translations Config
translations:
    default-file-location: /opt/i18n/translation_default.xlsx


# REST
api:
    base:
        path: /api/
    version: v1


##### Configuration for account management ####
task:
    account:
        delete:
             ## Task to remove expired password reset token
            expired.tokens: 15 10 * * * ?
            ## Task to remove inactive accounts
            ## At second :15 of minute :10 of every hour
            unactivated.accounts: 15 10 * * * ?
        ## Task to cancel account removal processes
        ## At second :15 of minute :20 of every hour
        cancel.account.deletion.proccess: 15 20 * * * ?
        ## Task for forwarding failed emails
        ## At second :00, every 5 minutes starting at minute :00, of every hour
        unsuccessful.mail.forwarding: 0 0/5 * * * ?
        ## Number of emails to be forwarded
        unsuccessful.mail.forwarding.number.of.emails.to.forward: 10