spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka:9092
                    auto-create-topics: true
                    configuration.auto.offset.reset: latest
            bindings:
                newUserRegistrationProcessor-in-0:
                    destination: new-user-registration-v1
                certificationCourseRegistration-in-0:
                    destination: course-registration-v1
                newCertificationRequest-in-0:
                    destination: new-certification-request-v1
                newTokensOrderApprovedProcessor-in-0:
                    destination: new-tokens-order-approved-v1
                notificationDeliveryRequestProcessor-in-0:
                    destination: notification-delivery-request-v1
                devicesManagementProcessor-in-0:
                    destination: devices-management-v1
            function:
                autodetect: false

# Stream Bridge Channels configuration
channels:
    new-user-registration: newUserRegistrationProcessor-in-0
    certification-course-registration: certificationCourseRegistration-int-0
    new-certification-request: newCertificationRequest-in-0
    new-tokens-order-approved: newTokensOrderApprovedProcessor-in-0
    notification-delivery-request: notificationDeliveryRequestProcessor-in-0
    device-management: devicesManagementProcessor-in-0

# JWT
jwt:
    token:
        header: Authorization
        secret: ENC(taz+v24xKk1PfMFbPCf6BKJ6iAzPIsC2reVW6JIzMU14vkKthnvjXPZO+dDxwT/i)
        expiration: 604800
    route:
        authentication:
            path: /auth
            refresh: refresh

# PayPal Gateway Config
paypal:
    client:
        id: ENC(Fl67YKHtgtLFXSIjkbBmfz0Q+EJoaIggezk7IzJWc5pKTHr7WHRP0FVj8I+/fOKy/OZ6J0SRaD5hpAdqYvhiDAbzQzPCaBwVgYZbqBydFtYYu1iZQJbUpXjlRVQhgeAM)
        secret: ENC(D2Xw9qRaLpqAAvpoUaB4YCo1r9Bif1lEYKO50JUEc9P2Qy09odVx7ifHIb9sL+hQOkXWMusQxWaFzPz5zavXH/ONTSxhtz4l44cWQQtVlDIoWm1dp3474MjyVd0KlZlB)

# Crypto Compare Gateway
cryptoCompare:
    baseUrl: https://min-api.cryptocompare.com
    apiKey: ENC(XX7EPAE/7iSPj+CQ0tHFA+jY1ITHXLf8iJh08R6W+u6IAuk5l28kIAVhHzDBWzH7PxTrLD++79pGuuN8Ih/MM4k35w/GMTTukOJIElMmmj4=)

# Translations Config
translations:
    default-file-location: /opt/i18n/translation_default.xlsx


# REST
api:
    base:
        path: /api/
    version: v1