spring:
  cloud:
    stream:
          function:
              definition: courseManagementProcessor
          kafka:
              binder:
                  brokers: kafka:9092
                  auto-create-topics: true
                  configuration.auto.offset.reset: latest
          default:
            consumer:
              concurrency: 2
          bindings:
            courseManagementProcessor-in-0:
              destination: course-management-v1
              group: tcs-course-events-processor
            courseManagementProcessor-out-0:
              destination: notification-delivery-request-v1