spring:
  cloud:
    stream:
          function:
              definition: newUserRegistrationProcessor;userRegisteredProcessor;newTokensOrderApprovedProcessor;tokensOrderCompletedProcessor
          kafka:
              binder:
                  brokers: kafka:9092
                  auto-create-topics: true
                  configuration.auto.offset.reset: latest
          default:
            consumer:
              concurrency: 2
          bindings:
              newUserRegistrationProcessor-in-0:
                  destination: new-user-registration-v1
                  group: tcs-user-events-processor
              newUserRegistrationProcessor-out-0:
                  destination: user-registered-v1
              userRegisteredProcessor-in-0:
                  destination: user-registered-v1
                  group: tcs-user-events-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              userRegisteredProcessor-out-0:
                  destination: notification-delivery-request-v1
              newTokensOrderApprovedProcessor-in-0:
                  destination: new-tokens-order-approved-v1
                  group: tcs-user-events-processor
              newTokensOrderApprovedProcessor-out-0:
                  destination: tokens-order-completed-v1
              tokensOrderCompletedProcessor-in-0:
                  destination: tokens-order-completed-v1
                  group: tcs-user-events-processor
                  consumer:
                      concurrency: 10
                      max-attempts: 3
              tokensOrderCompletedProcessor-out-0:
                  destination: notification-delivery-request-v1


# Tasks Config
task:
  ## Task to remove inactive accounts
  ## At second :15 of minute :10 of every hour
  delete.unactivated.accounts: 15 10 * * * ?
  ## Task to cancel account removal processes
  ## At second :15 of minute :20 of every hour
  cancel.account.deletion.proccess: 15 20 * * * ?
        