spring:
    cloud:
        stream:
            kafka:
                binder:
                    brokers: kafka:9092
                    auto-create-topics: true
                    configuration.auto.offset.reset: latest
            bindings:
                newUserRegistrationProcessor-out-0:
                    destination: new-user-registration-v1
                certificationCourseRegistration-out-0:
                    destination: course-registration-v1
                newCertificationRequest-out-0:
                    destination: new-certification-request-v1
                newTokensOrderApprovedProcessor-out-0:
                    destination: new-tokens-order-approved-v1
            function:
                autodetect: false

# JWT
jwt:
    token:
        header: Authorization
        secret: ENC(jE/+2/YpjTKkFpHbFlNzIVgpzHvwPhWo1+12ZaD3WLHGx5Ew+X2kvocuxV0qXp7Q)
        expiration: 604800
    route:
        authentication:
            path: /auth
            refresh: refresh


# REST
api:
    base:
        path: /api/
    version: v1


##### Configuration for account management ####
task:
    account:
        delete:
             ## Task to remove expired password reset token
            expired.tokens: 15 10 * * * ?
            ## Task to remove inactive accounts
            ## At second :15 of minute :10 of every hour
            unactivated.accounts: 15 10 * * * ?
        ## Task to cancel account removal processes
        ## At second :15 of minute :20 of every hour
        cancel.account.deletion.proccess: 15 20 * * * ?
        ## Task for forwarding failed emails
        ## At second :00, every 5 minutes starting at minute :00, of every hour
        unsuccessful.mail.forwarding: 0 0/5 * * * ?
        ## Number of emails to be forwarded
        unsuccessful.mail.forwarding.number.of.emails.to.forward: 10